### ISSUE TITLE
EventEmitter warnings in RN 0.65

### ISSUE THREAD

**Issue by radko93** [AgoraIO-Community/react-native-agora#412] opened 2021-09-15 11:55 UTC
In React Native 0.65 `removeListener` was deprecated and users of react-native-agora will get a warning every time Agora calls this function. Unfortunately I don't know if there is a backwards compatible way of fixing that yet. Similar PR https://github.com/react-native-modal/react-native-modal/pull/594

**Comment by LichKing-2234** [comment] 2021-09-17 02:24
duplicate of #409

**Comment by radko93** [comment] 2021-09-21 11:02
Hi, this is not related. The warnings are still there when using the code from my PR.

**Closed** 2021-11-30 05:51 UTC
